# Extra autostart processes
# exec-once = uwsm-app -- my-service

# Blue light filter, scheduled in ~/.config/hypr/hyprsunset.conf
exec-once = uwsm-app -- hyprsunset

# Which-key popup for submaps
exec-once = eww daemon
exec-once = ~/.config/eww/which-key-daemon.sh

# Disable notifications during screen sharing
exec-once = ~/.config/hypr/scripts/screencast-dnd
