# Extra autostart processes
# exec-once = uwsm-app -- my-service

# Blue light filter, scheduled in ~/.config/hypr/hyprsunset.conf
exec-once = uwsm-app -- hyprsunset

# Disable notifications during screen sharing
exec-once = ~/.config/hypr/scripts/screencast-dnd
